name: Deploy Node.js App

on:
  push:
    tags:
      - 'dev-*'
      - 'prod-*'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Load Environment Variables
        run: |
          if [[ "${{ github.ref }}" == *"dev-"* ]]; then
            echo "NODE_ENV=development" >> $GITHUB_ENV
            echo "DB_HOST=dev-db-host" >> $GITHUB_ENV
            echo "DB_USER=dev-db-user" >> $GITHUB_ENV
            echo "DB_PASSWORD=dev-db-password" >> $GITHUB_ENV
            echo "DB_NAME=dev-db-name" >> $GITHUB_ENV
          elif [[ "${{ github.ref }}" == *"prod-"* ]]; then
            echo "NODE_ENV=production" >> $GITHUB_ENV
            echo "DB_HOST=prod-db-host" >> $GITHUB_ENV
            echo "DB_USER=prod-db-user" >> $GITHUB_ENV
            echo "DB_PASSWORD=prod-db-password" >> $GITHUB_ENV
            echo "DB_NAME=prod-db-name" >> $GITHUB_ENV
          fi

      - name: Deploy to Server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_KEY }}
          SERVER_IP: ${{ secrets.SERVER_IP }}
          DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
        run: |
          echo "$DEPLOY_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key $DEPLOY_USER@$SERVER_IP << EOF
            cd /home/deploy/public_html2
            git pull origin master
            npm install
            if [[ "$NODE_ENV" == "development" ]]; then
              npm run dev
            else
              npm start
            fi
            sudo systemctl restart nginx
          EOF
