name: Deploy Node.js App

on:
  push:
    tags:
      - 'dev-*'
      - 'prod-*'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Load Environment Variables
        run: |
          if [[ "${{ github.ref }}" == *"dev-"* ]]; then
            echo "NODE_ENV=development" >> $GITHUB_ENV
          elif [[ "${{ github.ref }}" == *"prod-"* ]]; then
            echo "NODE_ENV=production" >> $GITHUB_ENV
          fi

      - name: Rsync Deployments
        uses: burnett01/rsync-deployments@7.0.2
        with:
          switches: -avzr --delete
          path: .
          remote_path: "/home/deploy/public_html"
          remote_host: 3.107.207.227
          remote_user: "deploy"
          remote_key: ${{ secrets.DEPLOY_KEY }}

      - name: Restart Application on Server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_KEY }}
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key deploy@3.107.207.227 << EOF
            cd /home/deploy/public_html
            npm install
            if [[ "$NODE_ENV" == "development" ]]; then
              npm run dev
            else
              npm start
            fi
            sudo systemctl restart nginx
          EOF
