name: Deploy Node.js App

on:
  push:
    branches:
      - master
    tags:
      - 'prod-*'

jobs:
  code-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

  ECR-push:
    runs-on: ubuntu-latest
    needs: code-tests
    if: startsWith(github.ref, 'refs/tags/')  # Run only if triggered by a tag
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      
      - name: Set up AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2 # Change to your AWS region
      
      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1
      
      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.ECR_URI }}:${{ github.ref_name }} .
      
      - name: Push Docker Image to ECR
        run: |
          docker push ${{ secrets.ECR_URI }}:${{ github.ref_name }}

   
